name: Remove preview on branch delete

on:
  delete:
    branches-ignore: 
      - main

jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Execute vercel remove
        run: vercel remove ${{ github.ref_name }}
      
