name: Deploy PR to GitHub Pages for preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Installing dependencies
        run: bun install

      - name: Building project
        run: bun run build

      - name: Deploy project to Github Pages for preview
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr/${{ github.event.pull_request.number }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
     - name: Checkout gh-pages branch
       run: |
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -rf pr/${{ github.event.pull_request.number }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Cleanup: Remove PR #${{ github.event.pull_request.number }} preview"
          git push
