name: Deploy PR to GitHub Pages for preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Installing dependencies
        run: bun install

      - name: Building project
        run: bun run build

      - name: Deploy branch to Netlify
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        run: |
          curl -X POST https://api.netlify.com/api/v1/sites/111c53d8-3527-4503-bc6a-153817c8e3ec/deploys \
               -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
               -F "branch=${{ github.head_ref }}" \
               -F "dir=./dist"
      
      
