name: Per-branch Deployment Preview

on:
  push:
    branches:
      - "!main"
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          project-name: 'per-branch'
          scope: "mavyfaby's projects"
          prod: false
